### ISSUE TITLE
Support for individual devops environments

### ISSUE THREAD

**Issue by jgsmith-usds** [USSBA/aws-cft-tools#16]
We want to be able to test out changes before we submit a PR, but we don't want to have to create a complete set of explicit environments for each infrastructure developer. We need a way to stand up an environment that has all the right things, but doesn't require us editing every template just to add our personal development environment.

The main thing is that as an infrastructure developer, I should be able to deploy my proposed changes to the templates without impacting anyone else, and without anyone else impacting me.

Some options:
1. require personal AWS accounts so a single "developer" environment can be deployed
2. support regex restrictions on environment values rather than just a list of acceptable values

Option (1) may require additional infrastructure in each AWS account, and keeping that additional infrastructure in sync is a separate problem, but tractable if we're using "infrastructure as code" techniques. This option allows "many" infrastructure developers to manage template development while restricting access to anything that is considered close to production. Similar to lower/upper, but with an addition tier below "lower."

Option (2) may require individual CIDRs if VPCs are peered. How would that be managed in a scalable, easy manner?

**Comment by bushong1** [comment]
I'm leaning towards Option 2, just because I feel like encouraging more aws accounts (without supporting an Account Factory model) is adding surface area for attack.

I think the idea would be best implemented by using a wild-card environment where we can, but using explicit environment names where required.  In this case, the Stack that has CIDR definitions would necessarily be hard-coded: 
```yaml
developer-charles:
  CIDRRange: 10.2.3.0/24
```
While other services can be primed with `developer-*` or something
```yaml
developer-*:
  InstanceSize: db.m3.medium
  MultiAZ: false
```

The act of forcing registration in a limited set of Stacks would be a good way to track what Environment stacks are available

**Comment by bushong1** [comment]
Another consideration/feature request that I've been tossing around would be allowing parameterized parameters in the case where the only thing we're replacing is the environment name.  This need is becoming apparent the more I use ParameterStore and DNS:
```yaml
dev:
  DNSName: dev.example.org
demo:
  DNSName: demo.example.org
stg:
  DNSName: stg.example.org
prod:
  DNSName: www.example.org
developer-charles: #proposed solution
  DNSName: developer-charles.example.org
```

Could be replaced with:
```yaml
default:
  DNSName: $ENV$.example.org
prod:
  DNSName: www.example.org
